# This file is machine-generated - editing it directly is not advised

[[ScientificTypes]]
path = "/Users/tlienart/.julia/dev/ScientificTypes"
uuid = "321657f4-b219-11e9-178b-2701a2544e81"
version = "0.6.0"
